sulphur/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('posts/<int:offset>/<int:limit>/', views.posts, name='posts'),
    path('navs/', views.navs, name='navs'),
    path('foots/', views.foots, name='foots'),
    path('pages/', views.pages, name='pages'),
    path('categories/', views.categories, name='categories'),

    path('add_post/', views.add_new_post, name='add_post'),
    path('add_nav/', views.add_nav, name='add_nav'),
    path('add_foot/', views.add_foot, name='add_foot'),
    path('add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category'),

    path('feed_new_post/', views.feed_new_post, name='feed_new_post'),
    path('feed_new_nav/', views.feed_new_nav, name='feed_new_nav'),
    path('feed_new_foot/', views.feed_new_foot, name='feed_new_foot'),
    path('feed_new_page/', views.feed_new_page, name='feed_new_page'),
    path('feed_new_category/', views.feed_new_category, name='feed_new_category'),

    path('single_post/<slug:cat>/<int:post_id>/<slug:post_title>/', views.single_post, name='single_post'),
    path('<slug:page_url>/', views.view_page, name='view_page'),
    path('<int:category_id>/<slug:category_url>/', views.category_page, name='category_page'),

    path('delete_post/<int:post_id>/', views.del_post, name='del_post'),
    path('delete_category/<int:category_id>/', views.del_category, name='del_category'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('delete_nav/<int:nav_id>/', views.delete_nav, name='delete_nav'),
    path('delete_foot/<int:foot_id>/', views.delete_foot, name='delete_foot'),

    path('edit_post/<slug:cat>/<int:post_id>/<slug:post_url>/', views.edit_post, name='edit_post'),
    path('edit_category/<int:category_id>/<slug:category_url>/', views.edit_category, name='edit_category'),
    path('edit_page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('edit_nav/<int:nav_id>/', views.edit_nav, name='edit_nav'),
    path('edit_foot/<int:foot_id>/', views.edit_foot, name='edit_foot'),

    path('publish_post/<int:post_id>/', views.publish_post, name='publish_post'),
    path('publish_category/<int:category_id>/', views.publish_category, name='publish_category'),
    path('publish_page/<int:page_id>/', views.publish_page, name='publish_page'),
    path('publish_nav/<int:nav_id>/', views.publish_nav, name='publish_nav'),
    path('publish_foot/<int:foot_id>/', views.publish_foot, name='publish_foot'),

    path('unpublish/<int:post_id>/', views.unpublish_post, name='unpublish_post'),
    path('unpublish_category/<int:category_id>/', views.unpublish_category, name='unpublish_category'),
    path('unpublish_page/<int:page_id>/', views.unpublish_page, name='unpublish_page'),
    path('unpublish_nav/<int:nav_id>/', views.unpublish_nav, name='unpublish_nav'),
    path('unpublish_foot/<int:foot_id>/', views.unpublish_foot, name='unpublish_foot'),
]

sulphur/sulphur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('themes.urls', namespace='themes')),
    path('config/', views.config, name='config'),
    path('sadmin/', include('sadmin.urls', namespace='sadmin')),
    path('sadmin/dashboard/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sulphur/blog/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from .models import Category

# Form for posting new post
class new_post_form(forms.Form):
    category_list = []
    
    categories = Category.objects.all()
    for record in categories:
        tup = (record.id, record.name)
        category_list.append(tup)

    
    title = forms.CharField(label='Title', max_length=60)

    cover_pic = forms.ImageField(label='Cover Pic')

    content = forms.CharField(widget=CKEditorUploadingWidget())

    keywords = forms.CharField(label='Keywords', max_length=60)

    description = forms.CharField(label='Description', max_length=300)

    category = forms.ChoiceField(label='Category', widget=forms.Select, choices=category_list)

# Form for posting new post
class xedit_post_form(forms.Form):
    category_list = []
    
    categories = Category.objects.all()
    for record in categories:
        tup = (record.id, record.name)
        category_list.append(tup)

    
    title = forms.CharField(label='Title', max_length=60)

    content = forms.CharField(widget=CKEditorUploadingWidget())

    keywords = forms.CharField(label='Keywords', max_length=60)

    description = forms.CharField(label='Description', max_length=300)

    category = forms.ChoiceField(label='Category', widget=forms.Select, choices=category_list)

# Form for posting new nav link
class new_nav_form(forms.Form):

    name = forms.CharField(label = 'Navlink Name', max_length=10)

    url = forms.URLField(widget=forms.URLInput())

# Form for posting new foot content
class new_foot_form(forms.Form):
    
    title = forms.CharField(label='Heading (Optional)', max_length=20, required=False)

    content = forms.CharField(label='Body', widget=CKEditorUploadingWidget())

    url = forms.URLField(label='Enter Link (Optional)', widget=forms.URLInput(), required=False)

# Form for posting new pages
class new_page_form(forms.Form):

    title = forms.CharField(label='Title', max_length=60)

    cover_pic = forms.ImageField(label='Cover Pic', required=False)

    content = forms.CharField(widget=CKEditorUploadingWidget(), required=False)

    keywords = forms.CharField(label='Keywords', max_length=60, required=False)

    description = forms.CharField(label='Description', max_length=300, required=False)

class xedit_page_form(forms.Form):

    title = forms.CharField(label='Title', max_length=60)

    content = forms.CharField(widget=CKEditorUploadingWidget(), required=False)

    keywords = forms.CharField(label='Keywords', max_length=60, required=False)

    description = forms.CharField(label='Description', max_length=300, required=False)


class new_category_form(forms.Form):
    
    name = forms.CharField(label='Category Name', max_length=20)

    cover_pic = forms.ImageField(label='Cover Pic')

    keywords = forms.CharField(label='Keywords', max_length=60)

    description = forms.CharField(label='Description', max_length=300)

class xedit_category_form(forms.Form):
    
    name = forms.CharField(label='Category Name', max_length=20)

    keywords = forms.CharField(label='Keywords', max_length=60)

    description = forms.CharField(label='Description', max_length=300)

sulphur/blog/views.py
from django.shortcuts import render, redirect
from sulphur.lib.fetcher import top_posts, all_navs, all_foots, all_pages, all_categories
from .forms import new_post_form, new_nav_form, new_foot_form, new_page_form, new_category_form, xedit_category_form, xedit_page_form, xedit_post_form
from django.utils import timezone
from sulphur.lib.authentication import is_loggedin
from django.template.defaultfilters import slugify
from .models import Post, Category
from sadmin.models import User


# ----------------- All Posts------------
#if the variable for pagination
def posts(request, offset, limit):
    if is_loggedin(request):
        record_list = top_posts(offset, limit)
        return render(request, 'blog/posts.html', {'record_list': record_list})
    else:
        msg = 'You`\re not logged in.'
        return render(request, 'debug.html', {'message': msg})
    
# It show the all nav links
def navs(request):
    if is_loggedin(request):
        nav_links = all_navs()
        return render(request, 'blog/navs.html', {'nav_links': nav_links})
    else:
        msg = 'You`\re not logged in.'
        return render(request, 'debug.html', {'message': msg})

# Show all the footer content
def foots(request):
    if is_loggedin(request):
        foot_list = all_foots()
        return render(request, 'blog/foots.html', {'foots': foot_list})
    else:
        msg = 'You`\re not logged in.'
        return render(request, 'debug.html', {'message': msg})

def pages(request):
    if is_loggedin(request):
        page_list = all_pages()
        return render(request, 'blog/pages.html', {'page_list': page_list})
    else:
        msg = 'You`\re not logged in.'
        return render(request, 'debug.html', {'message': msg})

def categories(request):
    if is_loggedin(request):
        category_list = all_categories()
        return render(request, 'blog/categories.html', {'category_list': category_list})
    else:
        msg = 'You`\re not logged in.'
        return render(request, 'debug.html', {'message': msg})


# ---------------- Add new post form---------
# It render the add new post form
def add_new_post(request):
    active = True
    if is_loggedin(request):
        return render(request, 'blog/new_post.html', {'active': active, 'new_post_form': new_post_form})
    else:
        active = False
        return render(request, 'blog/new_post.html', {'message': 'You can\'t add post, you are not logged in', 'active': active})

# It render the add new nav form
def add_nav(request):
    active = True
    if is_loggedin(request):
        return render(request, 'blog/new_nav.html', {'active': active, 'new_nav_form': new_nav_form})
    else:
        active = False
        return render(request, 'blog/new_nav.html', {'message': 'You can\'t add post, you are not logged in', 'active': active})

# It renders the add foot form  
def add_foot(request):
    active = True
    if is_loggedin(request):
        return render(request, 'blog/new_foot.html', {'active': active, 'new_foot_form': new_foot_form})
    else:
        active = False
        return render(request, 'blog/new_foot.html', {'message': 'You can\'t add post, you are not logged in', 'active': active})

# It render the add new page form
def add_page(request):
    active = True
    if is_loggedin(request):
        return render(request, 'blog/new_page.html', {'active': active, 'new_page_form': new_page_form})
    else:
        active = False
        return render(request, 'blog/new_post.html', {'message': 'You can\'t add post, you are not logged in', 'active': active})
    
def add_category(request):
    active= True
    if is_loggedin(request):
        return render(request, 'blog/new_category.html', {'active': active, 'new_category_form': new_category_form})
    else:
        active = False
        return render(request, 'blog/new_post.html', {'message': 'You can\'t add post, you are not logged in', 'active': active})

# --------------- Feeding into database------
# It add the new post data into database
def feed_new_post(request):

    if is_loggedin(request):
        if request.method == 'POST' or request.method == 'FILES':
            # Validating the form
            blog_post = new_post_form(request.POST, request.FILES)
            if blog_post.is_valid():
                #Extracting the data
                author = User.objects.get(login = request.session['username'])
                data = {
                    'title': blog_post.cleaned_data['title'],
                    'cover_pic': blog_post.cleaned_data['cover_pic'],
                    'content': blog_post.cleaned_data['content'],
                    'author': author,
                    'pub_date': timezone.now(),
                    'view_count': 0,
                    'url': slugify(blog_post.cleaned_data['title']),
                    'unlisted': 0,
                    'last_modified': timezone.now(),
                    'is_page': 0,
                    'in_nav': 0,
                    'in_footer': 0,
                    'keywords' : blog_post.cleaned_data['keywords'],
                    'description' : blog_post.cleaned_data['description'],
                    'social': 0,
                    'category': Category.objects.get(pk = blog_post.cleaned_data['category']),
                }
                # Instance of the Model Post
                n_p = Post(
                    title = data['title'],
                    cover_pic = data['cover_pic'],
                    content = data['content'],
                    author = data['author'],
                    pub_date = data['pub_date'],
                    view_count = data['view_count'],
                    url = data['url'],
                    unlisted = data['unlisted'],
                    last_modified = data['last_modified'],
                    is_page = data['is_page'],
                    in_nav = data['in_nav'],
                    in_footer = data['in_footer'],
                    keywords = data['keywords'],
                    description = data['description'],
                    social = data['social'],
                    category = data['category'],
                )
                n_p.save()
                return redirect('../posts/1/10/')
            else:
                msg = 'Form not cleaned. Page blog.views.py | Line 152'
                return render(request, 'debug.html', {'message': msg})
        else:
            msg = 'Invalid Access. Page blog.views.py | Line 26'
            return render(request, 'debug.html', {'message': msg})
    else:
        msg = 'Not logged in. Page blog.views.py | Line 29'
        return render(request, 'debug.html', {'message': msg})

# It will feed the new nav info into the database
def feed_new_nav(request):
    if is_loggedin(request):
        if request.method == 'POST':
            nav_form = new_nav_form(request.POST)
            if nav_form.is_valid():
                # Extracting Data
                author = User.objects.get(login=request.session['username'])
                data ={
                    'title': nav_form.cleaned_data['name'],
                    'content': '',
                    'author': author,
                    'pub_date': timezone.now(),
                    'view_count': 0,
                    'url': nav_form.cleaned_data['url'],
                    'unlisted': 0,
                    'last_modified': timezone.now(),
                    'is_page': 0,
                    'in_nav': 1,
                    'in_footer': 0,
                    'keywords': '',
                    'description': '',
                    'social': 0,
                }

                n_n = Post(
                    title = data['title'],
                    content = data['content'],
                    author = data['author'],
                    pub_date = data['pub_date'],
                    view_count = data['view_count'],
                    url = data['url'],
                    unlisted = data['unlisted'],
                    last_modified = data['last_modified'],
                    is_page = data['is_page'],
                    in_nav = data['in_nav'],
                    in_footer = data['in_footer'],
                    keywords = data['keywords'],
                    description = data['description'],
                    social = data['social'],
                )
                n_n.save()
                return redirect('../navs/')
            else:
                msg = 'Form not cleaned. Page blog.views.py | Line 175'
                return render(request, 'debug.html', {'message': msg})
        else:
            msg = 'Invalid Access. Page blog.views.py | Line 178'
            return render(request, 'debug.html', {'message': msg})
    else:
        msg = 'Not logged in. Page blog.views.py | Line 181'
        return render(request, 'debug.html', {'message': msg})

        
# Feed the footer data into database
def feed_new_foot(request):
    if is_loggedin(request):
        if request.method == 'POST':
            foot_form = new_foot_form(request.POST)
            if foot_form.is_valid():
                #Extracting Data
                author = User.objects.get(login=request.session['username'])
                data = {
                    'title': foot_form.cleaned_data['title'],
                    'content': foot_form.cleaned_data['content'],
                    'author': author,
                    'pub_date': timezone.now(),
                    'view_count': 0,
                    'url': foot_form.cleaned_data['url'],
                    'unlisted': 1,
                    'last_modified': timezone.now(),
                    'is_page': 0,
                    'in_nav': 0,
                    'in_footer': 1,
                    'keywords': '',
                    'description': '',
                    'social': 0,
                }
                n_f = Post(
                    title = data['title'],
                    content = data['content'],

sulphur/blog/templates/blog/categories.html
{% extends 'sadmin/admin_layout.html' %}

{% block styles %}
<style>
    h2{
        color: #5BC0DE;
    }
    .action-keys{
        color: #5BC0DE;
        font-size: 14px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h2 class="text-center">Hello {{request.session.display_name}}</h2>
    <h3>Categories &nbsp; <a href="{% url 'blog:add_category' %}" class="btn btn-info">Add New Category</a></h3>  
    <hr>
</div>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>    
                <th>Name</th>
                <th>Description</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for category in category_list %}
            
                <tr>
                    <td>{{category.id}}</td>
                    <td>{{category.name}}
                        <br>
                        <span class="action-keys">
                            <a href="{%url 'blog:del_category' category_id=category.id%}">delete</a>
                            |
                            <a href="{% url 'blog:edit_category' category_id=category.id category_url=category.url %}">edit</a>
                            |
                            {% if category.unlisted == 1 %}
                                <a href="{% url 'blog:publish_category' category_id=category.id %}">publish</a>
                            {% else %}
                                <a href="{% url 'blog:unpublish_category' category_id=category.id %}">unpublish</a>
                            {% endif %}
                        </span>
                    </td>
                    <td> {{category.description}} </td>
                    <td> {{category.date_created}} </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
</div>
{% endblock %}

sulphur/blog/templates/blog/category_page.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
    p{
        text-align: justify;
    }
</style>

<h1>I'm Single Category Page</h1>

<h1>{{category_obj.name}}</h1>


<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for record in category_posts %}
                <tr>
                    <td>
                        <a href="{% url 'blog:single_post' cat=record.category.url post_id=record.id post_title=record.url%}">
                            <b>{{record.title}}</b>
                        </a>
                            <br> <span class="action-keys">delete | edit | unpublish</span>
                    </td>
                    <td> {{record.description}}</td>
                    <td> {{record.author.display_name}} </td>
                    <td> {{record.pub_date}} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

sulphur/blog/templates/blog/edit_foot.html
{% extends 'sadmin/admin_layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container" id="list-heading">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Edit Foot</h1>
                <form action="{% url 'blog:edit_foot' foot_id=foot.id %}" method="POST">
                        {% csrf_token %}
                    <div class="form-group">
                        {{edit_foot_form.title.error}}
                        {{edit_foot_form.title.label_tag}}
                        {{edit_foot_form.title | add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        {{edit_foot_form.content.error}}
                        {{edit_foot_form.content | add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        {{edit_foot_form.url.error}}
                        {{edit_foot_form.url.label_tag}}
                        {{edit_foot_form.url | add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" value="Update" class="btn btn-info">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {% load static %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
{% endblock %}

sulphur/blog/templates/blog/edit_nav.html
{% extends 'sadmin/admin_layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Add Navigation Links</h1>
                <hr>
                <form action="{% url 'blog:edit_nav' nav_id=nav.id %}" method="POST">
                        {% csrf_token %}
                    <div class="form-group">
                        {{edit_nav_form.name.error}}
                        {{edit_nav_form.name.label_tag}}
                        {{edit_nav_form.name | add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        {{edit_nav_form.url.error}}
                        {{edit_nav_form.url.label_tag}}
                        {{edit_nav_form.url | add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" value="Update" class="btn btn-info">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {% load static %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
{% endblock %}

sulphur/blog/templates/blog/edit_page.html
{% extends 'sadmin/admin_layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Edit Post</h1>
            <form action="{% url 'blog:edit_page' page_id=page.id%}" method="POST">
                    {% csrf_token %}
                <div class="form-group">
                    {{edit_page_form.title.error}}
                    {{edit_page_form.title.label_tag}}
                    {{edit_page_form.title | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{edit_page_form.content.error}}
                    
                    {{edit_page_form.content| add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{edit_page_form.keywords.error}}
                    {{edit_page_form.keywords.label_tag}}
                    {{edit_page_form.keywords | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{edit_page_form.description.error}}
                    {{edit_page_form.description.label_tag}}
                    {{edit_page_form.description | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" value="Update" class="btn btn-info">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js'"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

sulphur/blog/templates/blog/foots.html
{% extends 'sadmin/admin_layout.html' %}

{% block styles %}
<style>
    h2{
        color: #5BC0DE;
    }
    .action-keys{
        color: #5BC0DE;
        font-size: 14px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container" id="list-heading">
    <h2 class="text-center">Hello {{request.session.display_name}}</h2>
    <h3>Footer Content &nbsp; <a href="{% url 'blog:add_foot' %}" class="btn btn-info">Add New</a></h3>  
    <hr>
</div>

<div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Content</th>
                <th>Author</th>
                <th>Date</th>
                <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
                {% for foot in foots %}
                    <tr>
                        <td>
                            {{foot.id}}.
                        </td>
                        <td>
                            <b>{{foot.title}}</b>
                        </td>
                        <td> {{foot.content}}
                            <br>
                            <span class="action-keys">
                                <a href="{% url 'blog:delete_foot' foot_id=foot.id %}">delete</a>
                                |
                                <a href="{% url 'blog:edit_foot' foot_id=foot.id %}">edit</a>
                                |
                                {% if foot.unlisted == 1 %}
                                    <a href="{% url 'blog:publish_foot' foot_id=foot.id %}">publish</a>
                                {% else %}
                                    <a href="{% url 'blog:unpublish_foot' foot_id=foot.id %}">unpublish</a>
                                {% endif %}
                            </span>
                        </td>
                        <td> {{foot.author.display_name}} </td>
                        <td> {{foot.pub_date}} </td>
                        <td> {{foot.last_modified}}</td>
                    </tr>
                </a>
                {% endfor %}
            </tbody>
            </table>
    </div>
{% endblock %}

sulphur/blog/templates/blog/new_category.html
{% extends 'sadmin/admin_layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Add Category</h1>
            <hr>
            <form action="{% url 'blog:feed_new_category' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                <div class="form-group">
                    {{new_category_form.name.error}}
                    {{new_category_form.name.label_tag}}
                    {{new_category_form.name|add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{new_category_form.cover_pic.error}}
                    {{new_category_form.cover_pic.label_tag}}
                    {{new_category_form.cover_pic|add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{new_category_form.keywords.error}}
                    {{new_category_form.keywords.label_tag}}
                    {{new_category_form.keywords | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{new_category_form.description.error}}
                    {{new_category_form.description.label_tag}}
                    {{new_category_form.description | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" value="submit" class="btn btn-info">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sulphur/blog/templates/blog/posts.html
{% extends 'sadmin/admin_layout.html' %}


{% block styles %}
<style>
    h2{
        color: #5BC0DE;
    }
</style>
{% endblock %}

{% block content %}
<div class="container" id="list-heading">
    <h3>All Posts &nbsp; <a href="{% url 'blog:add_post' %}" class="btn btn-info">Add New Post</a></h3>  
    <hr>
</div>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Category</th>
                <th>Author</th>
                <th>Date</th>
                <th>Last Modified</th>
            </tr>
        </thead>
        <tbody>
            {% for record in record_list %}
            
                <tr>
                    <td> {{record.id}} </td>
                    <td>
                        <a href="{% url 'blog:single_post' cat=record.category.url post_id=record.id post_title=record.url%}">
                            <b>{{record.title}}</b>
                        </a>
                        <br>
                        <span class="action-keys">
                            <a href="{%url 'blog:del_post' post_id=record.id%}"> delete </a>
                            | 
                            <a href="{% url 'blog:edit_post' cat=record.category.url post_id=record.id post_url=record.url%}">edit</a>
                            |
                            {% if record.unlisted == 1 %}
                                <a href="{% url 'blog:publish_post' post_id=record.id %}">publish</a>
                            {% else %}
                                <a href="{% url 'blog:unpublish_post' post_id=record.id %}">unpublish</a>
                            {% endif %}
                        </span>
                    </td>
                    <td> {{record.description}}</td>
                    <td> {{record.category.name}} </td>
                    <td> {{record.author.display_name}} </td>
                    <td> {{record.pub_date}} </td>
                    <td> {{record.last_modified}} </td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
</div>
{% endblock %}

sulphur/blog/templates/blog/view_page.html
{% extends 'sadmin/admin_layout.html' %}

{% block styles %}
<style>
    p{
        text-align: justify;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1> {{page_obj.title}} </h1>
    <hr>
    {{page_obj.content | safe}}
</div>
{% endblock %}