sulphur/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('posts/<int:offset>/<int:limit>/', views.posts, name='posts'),
    path('navs/', views.navs, name='navs'),
    path('foots/', views.foots, name='foots'),
    path('pages/', views.pages, name='pages'),
    path('categories/', views.categories, name='categories'),

    path('add_post/', views.add_new_post, name='add_post'),
    path('add_nav/', views.add_nav, name='add_nav'),
    path('add_foot/', views.add_foot, name='add_foot'),
    path('add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category'),

    path('feed_new_post/', views.feed_new_post, name='feed_new_post'),
    path('feed_new_nav/', views.feed_new_nav, name='feed_new_nav'),
    path('feed_new_foot/', views.feed_new_foot, name='feed_new_foot'),
    path('feed_new_page/', views.feed_new_page, name='feed_new_page'),
    path('feed_new_category/', views.feed_new_category, name='feed_new_category'),

    path('single_post/<slug:cat>/<int:post_id>/<slug:post_title>/', views.single_post, name='single_post'),
    path('<slug:page_url>/', views.view_page, name='view_page'),
    path('<int:category_id>/<slug:category_url>/', views.category_page, name='category_page'),

    path('delete_post/<int:post_id>/', views.del_post, name='del_post'),
    path('delete_category/<int:category_id>/', views.del_category, name='del_category'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('delete_nav/<int:nav_id>/', views.delete_nav, name='delete_nav'),
    path('delete_foot/<int:foot_id>/', views.delete_foot, name='delete_foot'),

    path('edit_post/<slug:cat>/<int:post_id>/<slug:post_url>/', views.edit_post, name='edit_post'),
    path('edit_category/<int:category_id>/<slug:category_url>/', views.edit_category, name='edit_category'),
    path('edit_page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('edit_nav/<int:nav_id>/', views.edit_nav, name='edit_nav'),
    path('edit_foot/<int:foot_id>/', views.edit_foot, name='edit_foot'),

    path('publish_post/<int:post_id>/', views.publish_post, name='publish_post'),
    path('publish_category/<int:category_id>/', views.publish_category, name='publish_category'),
    path('publish_page/<int:page_id>/', views.publish_page, name='publish_page'),
    path('publish_nav/<int:nav_id>/', views.publish_nav, name='publish_nav'),
    path('publish_foot/<int:foot_id>/', views.publish_foot, name='publish_foot'),

    path('unpublish/<int:post_id>/', views.unpublish_post, name='unpublish_post'),
    path('unpublish_category/<int:category_id>/', views.unpublish_category, name='unpublish_category'),
    path('unpublish_page/<int:page_id>/', views.unpublish_page, name='unpublish_page'),
    path('unpublish_nav/<int:nav_id>/', views.unpublish_nav, name='unpublish_nav'),
    path('unpublish_foot/<int:foot_id>/', views.unpublish_foot, name='unpublish_foot'),
]

sulphur/sulphur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('themes.urls', namespace='themes')),
    path('config/', views.config, name='config'),
    path('sadmin/', include('sadmin.urls', namespace='sadmin')),
    path('sadmin/dashboard/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sulphur/themes/urls.py
from django.urls import path
from . import views

app_name = 'themes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:category_id>/<slug:category_name>/', views.cat, name='cat'),
    path('<slug:category_name>/<int:post_id>/<slug:post_title>/', views.post, name='post'),
]

sulphur/themes/models.py
from django.db import models

# Create your models here.

sulphur/themes/views.py
from django.shortcuts import render
from blog.models import Post, Category
from sadmin.models import User
from sulphur.forms import signupform

# Create your views here.
def index(request):
    users = User.objects.all()
    if len(users) < 1:
        return render(request, 'config.html', {'signupform': signupform})
    else:   
        page = Post.objects.all()
        categories = Category.objects.filter(unlisted=0)
        return render(request, 'sulphate/index.html', {'page': page, 'categories': categories})

def cat(request, category_id, category_name):
    get_category = Category.objects.get(pk=category_id)
    posts = Post.objects.filter(category=get_category).filter(unlisted=0)
    return render(request, 'sulphate/category.html', {'posts': posts, 'category': get_category})

def post(request, category_name, post_id, post_title):
    post = Post.objects.get(pk=post_id)
    return render(request, 'sulphate/post.html', {'post': post})

sulphur/themes/templates/sulphate/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block page_title %}
            {% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">

        {% block metas %}
        {% endblock %}

        {% load staticfiles %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main-style.css' %}">

        <!-- Google Font Family -->
        <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Raleway|Roboto" rel="stylesheet">
        
        {% block css_files %}
        {% endblock %}

        {% block styles %}
        <style>
    #header1{
        background-image: url({{page.cover_pic.url}});
        border: 1px Solid Black;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: cover;
        position: relative;
        overflow: hidden;
    }
    #header-title{
        position: relative;
        top: 500px;
        left: 100px;
        color: White;
        font-weight: 700;
        font-size: 48px;
    }
    #header1 p{
        color: White;
        position: relative;
        top: 500px;
        left: 120px;
        font-size: 18px;
    }

    /* Categories */
    #categories{
        margin-top: 100px;
    }
    #categories h1{
        padding-bottom: 50px;
    }

    /* Category cards CSS */
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }
    .card-body{
        padding: 10px;
    }
</style>
        {% endblock %}
    </head>
    <body>
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                    <a class="navbar-brand" href="#">Sulphur</a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="/#categories">Categories</a></li>
                    </ul>
                </div>
            </nav>

        {% block content %}
        <div class="container-flex">
    <section id="header1">
        <h1 id='header-title'>{{page.title}}</h1>
        {{page.content|safe}}
    </section>
    <div class="container">
        {% load staticfiles %}
        <section id='categories'>
            <h1 class="text-center">All Categories</h1>
            <div class="row">
            {% for category in categories %}
                <a href="{% url 'themes:cat' category_id=category.id category_name=category.url %}">
                    <div class="col-md-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ category.cover_pic.url }}" alt="Card image" width="100%">
                            <div class="card-body">
                                <h4 class="card-title">{{category.name}}</h4>
                                <p class="card-text">Manage all your posts</p>
                            </div>
                        </div>  
                    </div>
                </a>
            {% endfor %}
            </div>
        </section>
    </div>
</div>
        {% endblock %}

        <footer>
            <div class="container-fluid">
                <p class="text-center">Copyright &copy; 2018 Sulphur Project</p>
                <h2 class="color text-center">Sulphur</h2>
            </div>
        </footer>

        {% load staticfiles %}
        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block js_files %}
        {% endblock %}

        {% block scripts %}
        <script>
        $(document).ready(function(){
            $('#header1').css({
                height: $(window).height()
            })

            $('#header-title').css({
                top: $(window).height() - 300
            })

            $('#header1 p').css({
                top: $(window).height() - 300
            })
        });
    </script>
        {% endblock %}
    </body>
</html>

sulphur/themes/templates/sulphate/category.html
{% extends 'sulphate/base.html' %}

{% block styles %}
<style>
    #cat-header{
        height: 500px;
        background-image: url({{category.cover_pic.url}});
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    #posts h1{
        padding-top: 50px;
        padding-bottom: 50px;
    }
</style>
{% endblock %}

{% block content %}
    <div id='cat-header'>
    </div>

    <div class="container">
        {% load staticfiles %}
        <section id='posts'>
            <h1 class="text-center"> {{category.name}} </h1>
            <div class="row">
            {% for post in posts %}
                <a href="{% url 'themes:post' category_name=category.url post_id=post.id post_title=post.url %}">
                    <div class="col-md-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ post.cover_pic.url }}" alt="Card image" width="100%">
                            <div class="card-body">
                                <h4 class="card-title">{{post.title}}</h4>
                            </div>
                        </div>  
                    </div>
                </a>
            {% endfor %}
            </div>
        </section>
    </div>

{% endblock %}

sulphur/themes/templates/sulphate/index.html
{% extends 'sulphate/base.html' %}

{% block styles %}
<style>
    #header1{
        background-image: url({{page.cover_pic.url}});
        border: 1px Solid Black;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: cover;
        position: relative;
        overflow: hidden;
    }
    #header-title{
        position: relative;
        top: 500px;
        left: 100px;
        color: White;
        font-weight: 700;
        font-size: 48px;
    }
    #header1 p{
        color: White;
        position: relative;
        top: 500px;
        left: 120px;
        font-size: 18px;
    }

    /* Categories */
    #categories{
        margin-top: 100px;
    }
    #categories h1{
        padding-bottom: 50px;
    }

    /* Category cards CSS */
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }
    .card-body{
        padding: 10px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-flex">
    <section id="header1">
        <h1 id='header-title'>{{page.title}}</h1>
        {{page.content|safe}}
    </section>
    <div class="container">
        {% load staticfiles %}
        <section id='categories'>
            <h1 class="text-center">All Categories</h1>
            <div class="row">
            {% for category in categories %}
                <a href="{% url 'themes:cat' category_id=category.id category_name=category.url %}">
                    <div class="col-md-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ category.cover_pic.url }}" alt="Card image" width="100%">
                            <div class="card-body">
                                <h4 class="card-title">{{category.name}}</h4>
                                <p class="card-text">Manage all your posts</p>
                            </div>
                        </div>  
                    </div>
                </a>
            {% endfor %}
            </div>
        </section>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('#header1').css({
                height: $(window).height()
            })

            $('#header-title').css({
                top: $(window).height() - 300
            })

            $('#header1 p').css({
                top: $(window).height() - 300
            })
        });
    </script>
{% endblock %}
0

sulphur/themes/templates/sulphate/post.html
{% extends 'sulphate/base.html' %}

{% block styles %}
<style>
    #body{
        margin-top: 60px;
    }
</style>
{% endblock %}

{% block content %}

<div class="container" id="body">
    <h1> {{post.title}} </h1>
    {{post.content|safe}}
</div>

{% endblock %}