sulphur/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('posts/<int:offset>/<int:limit>/', views.posts, name='posts'),
    path('navs/', views.navs, name='navs'),
    path('foots/', views.foots, name='foots'),
    path('pages/', views.pages, name='pages'),
    path('categories/', views.categories, name='categories'),

    path('add_post/', views.add_new_post, name='add_post'),
    path('add_nav/', views.add_nav, name='add_nav'),
    path('add_foot/', views.add_foot, name='add_foot'),
    path('add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category'),

    path('feed_new_post/', views.feed_new_post, name='feed_new_post'),
    path('feed_new_nav/', views.feed_new_nav, name='feed_new_nav'),
    path('feed_new_foot/', views.feed_new_foot, name='feed_new_foot'),
    path('feed_new_page/', views.feed_new_page, name='feed_new_page'),
    path('feed_new_category/', views.feed_new_category, name='feed_new_category'),

    path('single_post/<slug:cat>/<int:post_id>/<slug:post_title>/', views.single_post, name='single_post'),
    path('<slug:page_url>/', views.view_page, name='view_page'),
    path('<int:category_id>/<slug:category_url>/', views.category_page, name='category_page'),

    path('delete_post/<int:post_id>/', views.del_post, name='del_post'),
    path('delete_category/<int:category_id>/', views.del_category, name='del_category'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('delete_nav/<int:nav_id>/', views.delete_nav, name='delete_nav'),
    path('delete_foot/<int:foot_id>/', views.delete_foot, name='delete_foot'),

    path('edit_post/<slug:cat>/<int:post_id>/<slug:post_url>/', views.edit_post, name='edit_post'),
    path('edit_category/<int:category_id>/<slug:category_url>/', views.edit_category, name='edit_category'),
    path('edit_page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('edit_nav/<int:nav_id>/', views.edit_nav, name='edit_nav'),
    path('edit_foot/<int:foot_id>/', views.edit_foot, name='edit_foot'),

    path('publish_post/<int:post_id>/', views.publish_post, name='publish_post'),
    path('publish_category/<int:category_id>/', views.publish_category, name='publish_category'),
    path('publish_page/<int:page_id>/', views.publish_page, name='publish_page'),
    path('publish_nav/<int:nav_id>/', views.publish_nav, name='publish_nav'),
    path('publish_foot/<int:foot_id>/', views.publish_foot, name='publish_foot'),

    path('unpublish/<int:post_id>/', views.unpublish_post, name='unpublish_post'),
    path('unpublish_category/<int:category_id>/', views.unpublish_category, name='unpublish_category'),
    path('unpublish_page/<int:page_id>/', views.unpublish_page, name='unpublish_page'),
    path('unpublish_nav/<int:nav_id>/', views.unpublish_nav, name='unpublish_nav'),
    path('unpublish_foot/<int:foot_id>/', views.unpublish_foot, name='unpublish_foot'),
]

sulphur/sulphur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('themes.urls', namespace='themes')),
    path('config/', views.config, name='config'),
    path('sadmin/', include('sadmin.urls', namespace='sadmin')),
    path('sadmin/dashboard/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sulphur/sulphur/forms.py
from django import forms

class signupform(forms.Form):
    genderOptions = [
        (1, 'male'),
        (0, 'female'),
    ]
    username = forms.CharField(label='Username', max_length=60)
    password = forms.CharField(widget=forms.PasswordInput)
    full_name = forms.CharField(label='Full Name', max_length=50)
    gender = forms.ChoiceField(label='Gender', widget=forms.RadioSelect, choices=genderOptions)
    email = forms.EmailField()

sulphur/sulphur/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from hashlib import sha256
from .lib.utils import first_word
from sadmin.models import User
from .forms import signupform

#If any user is there, so it sends to the index page, else configuration page is visible
def index(request):
    users = User.objects.all()
    if len(users) < 1:
        return render(request, 'config.html', {'signupform': signupform})
    else:
        return render(request, 'index.html')

def config(request):
    if request.method == 'POST':
        
        #Checking the incoming form with the defined form class
        configform = signupform(request.POST)
        if configform.is_valid():

            #Collecting the cleaned data
            data = {
                'username': configform.cleaned_data['username'],
                'password': configform.cleaned_data['password'],
                'full_name': configform.cleaned_data['full_name'],
                'email': configform.cleaned_data['email'],
                'gender': configform.cleaned_data['gender'],
                'reg_date': timezone.now(),
                'last_modified': timezone.now(),
                'user_pic': 'default.jpg',
                'display_name': first_word(configform.cleaned_data['full_name']),
            }

            # This is the instance of the model User
            new_user = User(
                login = data['username'],
                password =  sha256(data['password'].encode('utf-8')).hexdigest(),
                full_name = data['full_name'],
                gender = data['gender'],
                email = data['email'],
                reg_date = data['reg_date'],
                display_name = first_word(data['full_name']),
                last_modified = data['last_modified'],
                user_pic = data['user_pic'],
            )
            # return render(request, 'debug.html', data)
            # Feeding in the database
            new_user.save()

            #Creating the login session
            request.session['active'] = True
            current_user = User.objects.get(login = data['username'])
            
            request.session['username'] = current_user.login
            request.session['full_name'] = current_user.full_name
            request.session['gender'] = current_user.gender
            request.session['email'] = current_user.email

            request.session['reg_date_year'] = current_user.reg_date.year
            request.session['reg_date_month'] = current_user.reg_date.month
            request.session['reg_date_day'] = current_user.reg_date.day
            request.session['reg_date_hour'] = current_user.reg_date.hour
            request.session['reg_date_minute'] = current_user.reg_date.minute
            request.session['reg_date_second'] = current_user.reg_date.second

            
            request.session['display_name'] = current_user.display_name
        
            request.session['last_modified_year'] = current_user.last_modified.year
            request.session['last_modified_month'] = current_user.last_modified.month
            request.session['last_modified_day'] = current_user.last_modified.day
            request.session['last_modified_hour'] = current_user.last_modified.hour
            request.session['last_modified_minute'] = current_user.last_modified.minute
            request.session['last_modified_second'] = current_user.last_modified.second

            request.session['user_pic'] = current_user.user_pic


            #Sending user onto login page from where it will be redirected to the dashboard
            return redirect('/sadmin/')


        else:
            msg = {
                'message': 'Config Form is Invalid [sulphur.views.py Line: 87]',
            }
            return render(request, 'debug.html', msg)
    else:
        msg = {
                # 'message': 'INVALID ACCESS | Request Method is  n\'t  POST [sulphur.views.py line:92]',/
                'message': request.method
            }
        return render(request, 'debug.html', msg)

sulphur/sulphur/templates/config.html
{% extends 'sadmin/basic_layout.html' %}
{% load widget_tweaks %}

{% block styles %}
<style>
    h1{
        font-size: 60px;
        padding-top: 100px;
    }
    #config-form{
        margin-top: 60px;
    }
    #id_gender{
        list-style: none;
        padding-left: 20px;
    }
    #id_gender li{
        display: inline-block;
        padding-right: 20px;
    }
</style>
{% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-center color">SULPHUR</h1>
    </div>
    <div class="container">
        <div class="row">
            <form action="{% url 'config' %}" method="POST" class="col-md-4 col-md-offset-4" id="config-form">
                {% csrf_token %}
                <div class="form-group">
                    {{signupform.username.error}}
                    {{signupform.username.label_tag}}
                    {{signupform.username | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{signupform.full_name.error}}
                    {{signupform.full_name.label_tag}}
                    {{signupform.full_name | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{signupform.gender.error}}
                    {{signupform.gender.label_tag}}
                    {{signupform.gender}}
                </div>
                <div class="form-group">
                    {{signupform.email.error}}
                    {{signupform.email.label_tag}}
                    {{signupform.email | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{signupform.password.error}}
                    {{signupform.password.label_tag}}
                    {{signupform.password| add_class:"form-control"}}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" value="Submit" class="btn btn-default form-control">
                </div>
            </form>
        </div>
    </div>
    
{% endblock %}

sulphur/sulphur/templates/debug.html
<h1>I'm debug page</h1>

{{message}}

sulphur/sulphur/templates/index.html
<h1>I'm index page</h1>

sulphur/sulphur/templates/page.html
{% extends 'sulphate/base.html' %}

{% block styles %}
<style>
    #body{
        margin-top: 60px;
    }
</style>
{% endblock %}

{% block content %}

<div class="container" id="body">
    <h1> {{post.title}} </h1>
    {{post.content|safe}}
</div>

{% endblock %}