sulphur/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('posts/<int:offset>/<int:limit>/', views.posts, name='posts'),
    path('navs/', views.navs, name='navs'),
    path('foots/', views.foots, name='foots'),
    path('pages/', views.pages, name='pages'),
    path('categories/', views.categories, name='categories'),

    path('add_post/', views.add_new_post, name='add_post'),
    path('add_nav/', views.add_nav, name='add_nav'),
    path('add_foot/', views.add_foot, name='add_foot'),
    path('add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category'),

    path('feed_new_post/', views.feed_new_post, name='feed_new_post'),
    path('feed_new_nav/', views.feed_new_nav, name='feed_new_nav'),
    path('feed_new_foot/', views.feed_new_foot, name='feed_new_foot'),
    path('feed_new_page/', views.feed_new_page, name='feed_new_page'),
    path('feed_new_category/', views.feed_new_category, name='feed_new_category'),

    path('single_post/<slug:cat>/<int:post_id>/<slug:post_title>/', views.single_post, name='single_post'),
    path('<slug:page_url>/', views.view_page, name='view_page'),
    path('<int:category_id>/<slug:category_url>/', views.category_page, name='category_page'),

    path('delete_post/<int:post_id>/', views.del_post, name='del_post'),
    path('delete_category/<int:category_id>/', views.del_category, name='del_category'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('delete_nav/<int:nav_id>/', views.delete_nav, name='delete_nav'),
    path('delete_foot/<int:foot_id>/', views.delete_foot, name='delete_foot'),

    path('edit_post/<slug:cat>/<int:post_id>/<slug:post_url>/', views.edit_post, name='edit_post'),
    path('edit_category/<int:category_id>/<slug:category_url>/', views.edit_category, name='edit_category'),
    path('edit_page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('edit_nav/<int:nav_id>/', views.edit_nav, name='edit_nav'),
    path('edit_foot/<int:foot_id>/', views.edit_foot, name='edit_foot'),

    path('publish_post/<int:post_id>/', views.publish_post, name='publish_post'),
    path('publish_category/<int:category_id>/', views.publish_category, name='publish_category'),
    path('publish_page/<int:page_id>/', views.publish_page, name='publish_page'),
    path('publish_nav/<int:nav_id>/', views.publish_nav, name='publish_nav'),
    path('publish_foot/<int:foot_id>/', views.publish_foot, name='publish_foot'),

    path('unpublish/<int:post_id>/', views.unpublish_post, name='unpublish_post'),
    path('unpublish_category/<int:category_id>/', views.unpublish_category, name='unpublish_category'),
    path('unpublish_page/<int:page_id>/', views.unpublish_page, name='unpublish_page'),
    path('unpublish_nav/<int:nav_id>/', views.unpublish_nav, name='unpublish_nav'),
    path('unpublish_foot/<int:foot_id>/', views.unpublish_foot, name='unpublish_foot'),
]

sulphur/sadmin/urls.py
from . import views
from django.urls import path

app_name = 'sadmin'
urlpatterns = [
    path('', views.sadmin, name='sadmin'),
    path('login/', views.login, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
]

sulphur/sulphur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('themes.urls', namespace='themes')),
    path('config/', views.config, name='config'),
    path('sadmin/', include('sadmin.urls', namespace='sadmin')),
    path('sadmin/dashboard/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sulphur/sadmin/models.py
from django.db import models

# Create your models here.
class User(models.Model):

    # login id of the user e.gg sirajalam049
    login = models.CharField(max_length=60)

    # password of the user when logging in
    password = models.CharField(max_length=250)

    # full name of the user
    full_name = models.CharField(max_length=50)

    # gender of the user. 0 means female and 1 for male
    gender = models.BooleanField(default=1)

    # email address of the user for reset the password
    email = models.EmailField()

    # Date of registration
    reg_date = models.DateTimeField()

    # Name to be displayed when logged in
    display_name = models.CharField(max_length=30)

    # When the post is modified last time
    last_modified = models.DateTimeField()

    # Profile picture for the user
    user_pic = models.CharField(max_length=250)

    def __str__(self):
        return self.full_name

sulphur/sadmin/forms.py
from django import forms

class loginform(forms.Form):
    username = forms.CharField(label='Username', max_length=60)
    password = forms.CharField(widget=forms.PasswordInput)

sulphur/sadmin/views.py
from django.shortcuts import render, redirect
from .forms import loginform
from sulphur.lib import authentication
from .models import User
from hashlib import sha256
# Create your views here.



def sadmin(request):
    if authentication.is_loggedin(request):
        return redirect('dashboard/')
    else:
        return render(request, 'sadmin/login.html', {'loginform' : loginform})

# This will login the user and send to the dashboard
def login(request):
    # Checking if the user is already loggedin
    if authentication.is_loggedin(request):
        return redirect('../dashboard/')
    else:
        # Validating the login form came from login.html
        logindetails = loginform(request.POST)

        if logindetails.is_valid():
            # Extracting the data from login form
            data = {
                'username': logindetails.cleaned_data['username'],
                'password': logindetails.cleaned_data['password'],
            }
            data['password'] = sha256(data['password'].encode('utf-8')).hexdigest()

            # Getting the record by username
            try:
                u =  User.objects.get(login = data['username'])
            # sending to login if it is wrong
            except User.DoesNotExist:
                return render(request, 'sadmin/login.html', {'loginform': loginform, 'message': 'Username is incorrect',})
            
            if u.password == data['password']:
                # logging in
                request.session['active'] = True

                # Adding the current logged in data into the session
                request.session['id'] = u.id
                request.session['username'] = u.login
                request.session['full_name'] = u.full_name
                request.session['gender'] = u.gender
                request.session['email'] = u.email
                
                request.session['reg_date_year'] = u.reg_date.year
                request.session['reg_date_month'] = u.reg_date.month
                request.session['reg_date_day'] = u.reg_date.day
                request.session['reg_date_hour'] = u.reg_date.hour
                request.session['reg_date_minute'] = u.reg_date.minute
                request.session['reg_date_second'] = u.reg_date.second

                request.session['display_name'] = u.display_name
                
                request.session['last_modified_year'] = u.last_modified.year
                request.session['last_modified_month'] = u.last_modified.month
                request.session['last_modified_day'] = u.last_modified.day
                request.session['last_modified_hour'] = u.last_modified.hour
                request.session['last_modified_minute'] = u.last_modified.minute
                request.session['last_modified_second'] = u.last_modified.second

                request.session['user_pic'] = u.user_pic

                return redirect('/sadmin/')
            else:
                return render(request, 'sadmin/login.html', {'loginform': loginform, 'message': 'Password is incorrect'})
        else:
            return render(request, 'sadmin/login.html', {'loginform': loginform, 'message': 'Form is not valid [sadmin.views.py Line: 57]'})
            

def logout(request):
    authentication.logout(request)
    return redirect('/')
        
def dashboard(request):
    if authentication.is_loggedin(request):
        return render(request, 'sadmin/dashboard.html')
    else:
        return redirect('../')



            

sulphur/sadmin/templates/sadmin/admin_layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title_of_page %}
            {% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        {% load staticfiles %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Google Font Family -->
        <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Raleway|Roboto" rel="stylesheet">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <link rel="stylesheet" href="{% static 'css/main-style.css' %}">
        <link rel="stylesheet" href="{% static 'css/admin-style.css' %}">
        
        {% block cssfiles %}
        {% endblock %}

        {% block styles %}
        {% endblock %}
    </head>
    <body>

        <header>
            <div class="container-fluid" id="admin-panel">
                <div class="row text-center">
                    <div class="col-md-3"><p><a href="{% url 'sadmin:dashboard' %}">Dashboard</a></p></div>
                    <div class="col-md-6"><p>Welcome, {{ request.session.display_name }} Sir</p></div>
                    <div class="col-md-3"><p><a href="{% url 'sadmin:logout' %}">Logout</a></p></div>
                </div>
            </div>
        </header>

        {% block header%}
        {% endblock %}
        
        {% block content %}
        {% endblock %}

        <footer>
            <div class="container-fluid">
                <p class="text-center">Copyright &copy; 2018 Sulphur Project</p>
                <h2 class="color text-center">Sulphur</h2>
            </div>
        </footer>

        {% load staticfiles %}
        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

sulphur/sadmin/templates/sadmin/basic_layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title_of_page %}
            {% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        {% load staticfiles %}

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Google Font Family -->
        <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Raleway|Roboto" rel="stylesheet">
        
        <link rel="stylesheet" href="{% static 'css/main-style.css' %}">
        <link rel="stylesheet" href="{% static 'css/admin-style.css' %}">
        
        {% block cssfiles %}
        {% endblock %}

        {% block styles %}
        {% endblock %}
    </head>
    <body>
        {% block header%}
        {% endblock %}
        
        {% block content %}
        {% endblock %}

        {% block footer%}
        {% endblock %}

        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

sulphur/sadmin/templates/sadmin/dashboard.html
{% extends 'sadmin/admin_layout.html' %}

{% block styles %}
    <style>
        #main-options{
            margin-top: 70px;
        }
        #main-options .row{
            margin: 30px 0;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
        .card-body{
            padding: 10px;
        }
        #main-options h1{
            margin-bottom: 70px;
        }
    </style>
{% endblock %}

{% block content %}
{% load staticfiles %}
    <div class="container" id="main-options">
        <h1 class="text-center color">Sulphur</h1>
        <div class="row">
            <a href="{% url 'blog:posts' offset=1 limit=10 %}">
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/dash/blog.jpg' %}" alt="Card image" width="100%">
                        <div class="card-body">
                            <h4 class="card-title">Posts</h4>
                            <p class="card-text">Manage all your posts</p>
                        </div>
                    </div>  
                </div>
            </a>
            <a href="{% url 'blog:pages' %}">
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/dash/pages.jpg' %}" alt="Card image" width="100%">
                        <div class="card-body">
                            <h4 class="card-title">Pages</h4>
                            <p class="card-text">Manage all your static pages</p>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'blog:navs' %}">
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/dash/header.jpg' %}" alt="Card image" width="100%">
                        <div class="card-body">
                            <h4 class="card-title">Header</h4>
                            <p class="card-text">Manage all your posts</p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="row">
            <a href="{% url 'blog:foots' %}">
                <div class="col-md-4 col-md-offset-2">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/dash/footer.jpg' %}" alt="Card image" width="100%">
                        <div class="card-body">
                            <h4 class="card-title">Footer</h4>
                            <p class="card-text">Manage all your posts</p>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'blog:categories' %}">
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/dash/dishes.jpg' %}" alt="Card image" width="100%">
                        <div class="card-body">
                            <h4 class="card-title">Category</h4>
                            <p class="card-text">Manage all your posts</p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

sulphur/sadmin/templates/sadmin/login.html
{% extends 'sadmin/basic_layout.html' %}
{% load widget_tweaks %}

{% block styles %}
<style>
    h1{
        padding-top: 100px;
    }
    #login-form{
        margin-top: 60px;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center color">Login</h1>
    </div>
    <div class="container">
        <div class="row">
            <form action="{% url 'sadmin:login' %}" method="POST" class="col-md-4 col-md-offset-4" id="login-form">
                {% csrf_token %}
                <div class="form-group">
                    {{loginform.username.error}}
                    {{loginform.username.label_tag}}
                    {{loginform.username | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    {{loginform.password.error}}
                    {{loginform.password.label_tag}}
                    {{loginform.password | add_class:"form-control"}}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" value="Submit" class="btn btn-default form-control">
                </div>
            </form>
        </div>
    </div>
{% endblock %}